import { Token } from "@/types/Token";
import {bsc, mainnet, polygon, arbitrum, avalanche, base, optimism} from "viem/chains";

export const tokenList: Token[] = [
  {
    chainId: bsc.id,
    symbol: "BNB",
    name: "BNB",
    address: undefined,
    logoURI: "/images/tokens/bnb.svg",
    decimals: 18,
  },
  {
    chainId: polygon.id,
    symbol: "MATIC",
    name: "MATIC",
    address: undefined,
    logoURI: "/images/tokens/matic.svg",
    decimals: 18,
  },
  {
    chainId: arbitrum.id,
    symbol: "ARB",
    name: "ARB",
    address: undefined,
    logoURI: "/images/tokens/arbitrum-arb-logo.svg",
    decimals: 18,
  },
  {
    chainId: avalanche.id,
    symbol: "AVAX",
    name: "AVAX",
    address: undefined,
    logoURI: "/images/tokens/avalanche-avax-logo.svg",
    decimals: 18,
  },
  {
    chainId: base.id,
    symbol: "BASE",
    name: "BASE",
    address: undefined,
    logoURI: "/108554348.png",
    decimals: 18,
  },
  {
    chainId: optimism.id,
    symbol: "OP",
    name: "OP",
    address: undefined,
    logoURI: "/images/tokens/optimism-ethereum-op-logo.svg",
    decimals: 18,
  },
  {
    chainId: mainnet.id,
    symbol: "ETH",
    name: "ETH",
    address: undefined,
    logoURI: "/images/tokens/eth.svg",
    decimals: 18,
  },
  {
    chainId: 55555,
    symbol: "USDC",
    name: "USDC",
    address: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff",
    logoURI: "/images/tokens/usdc.svg",
    decimals: 6,
  },
  {
    chainId: 666666,
    symbol: "USDT",
    name: "USDT",
    address: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff",
    logoURI: "/images/tokens/usdt.svg",
    decimals: 6,
  },
  {
    chainId: 7777777,
    symbol: "WETH",
    name: "WETH",
    address: undefined,
    logoURI: "/images/tokens/eth.svg",
    decimals: 18,
  },
  {
    chainId: bsc.id,
    symbol: "BNB",
    name: "BNB",
    address: undefined,
    logoURI: "/images/tokens/bnb.svg",
    decimals: 18,
  },
  {
    chainId: polygon.id,
    symbol: "MATIC",
    name: "MATIC",
    address: undefined,
    logoURI: "/images/tokens/matic.svg",
    decimals: 18,
  },
  {
    chainId: arbitrum.id,
    symbol: "ARB",
    name: "ARB",
    address: undefined,
    logoURI: "/images/tokens/arbitrum-arb-logo.svg",
    decimals: 18,
  },
  {
    chainId: avalanche.id,
    symbol: "AVAX",
    name: "AVAX",
    address: undefined,
    logoURI: "/images/tokens/avalanche-avax-logo.svg",
    decimals: 18,
  },
  {
    chainId: base.id,
    symbol: "BASE",
    name: "BASE",
    address: undefined,
    logoURI: "/108554348.png",
    decimals: 18,
  },
  {
    chainId: optimism.id,
    symbol: "OP",
    name: "OP",
    address: undefined,
    logoURI: "/images/tokens/optimism-ethereum-op-logo.svg",
    decimals: 18,
  },
  {
    chainId: mainnet.id,
    symbol: "ETH",
    name: "ETH",
    address: undefined,
    logoURI: "/images/tokens/eth.svg",
    decimals: 18,
  },
  {
    chainId: 55555,
    symbol: "USDC",
    name: "USDC",
    address: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff",
    logoURI: "/images/tokens/usdc.svg",
    decimals: 6,
  },
  {
    chainId: 666666,
    symbol: "USDT",
    name: "USDT",
    address: "0x176211869cA2b568f2A7D4EE941E073a821EE1ff",
    logoURI: "/images/tokens/usdt.svg",
    decimals: 6,
  },
  {
    chainId: 7777777,
    symbol: "WETH",
    name: "WETH",
    address: undefined,
    logoURI: "/images/tokens/eth.svg",
    decimals: 18,
  },
];
